version: "3.3"

services:
  bui-api-login:
    image: bui-api-login:latest
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.local

    volumes:
      - /Users/vesko/coding/toni/bui2/local/data/bui_api_login:/app/config
 